### ISSUE TITLE
handle CF domain adding gracefully

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-beamup#3]
in `beamup-sync-swarm`, we just try to add A records for all apps; this results in errors when they already exist

Instead, first check if they already exist. Or just modify the error handling to ignore errors that return "already exists"

**Comment by shteryana** [comment]
Done in https://github.com/Stremio/stremio-beamup/blob/067fa5d0c0e6913b1d4ef33fe13414fc0701e012/swarm-syncer/beamup-sync-swarm#L97
