### ISSUE TITLE
Project one-piece-turkce-altyazi Removal

### ISSUE THREAD

**Issue by osmansonsuz** [Stremio/stremio-beamup#39]
I have accidently permanently deleted my public-private keys. Now i dont have access to my project. I would like you tou delete my project please. 

https://fdfa3f0d051a-one-piece-turkce-altyazi.baby-beamup.club

**Comment by gcalcaterra** [comment]
Hi @osmansonsuz. Did you use another GitHub account to deploy your addon? If so, do you have a way to write a comment here with that account? In that way to verify your ownership. Thanks.

**Comment by osmansonsuz** [comment]
No. As i remember i have used this account.

**Comment by osmansonsuz** [comment]
> Hi @osmansonsuz. Did you use another GitHub account to deploy your addon? If so, do you have a way to write a comment here with that account? In that way to verify your ownership. Thanks.
No. As i remember i have used this account.

**Comment by holyinfinity** [comment]
> Hi @osmansonsuz. Did you use another GitHub account to deploy your addon? If so, do you have a way to write a comment here with that account? In that way to verify your ownership. Thanks.

To make sure i am writing with my other accounts.

**Comment by dexter21767-dev** [comment]
@osmansonsuz just to clear things out. in the addon URL https://fdfa3f0d051a-one-piece-turkce-altyazi.baby-beamup.club/
one-piece-turkce-altyazi: is the addon name u specified while doing 'beamup init'
fdfa3f0d051a: is a unique ID derived from your github username.
and that ID doesn't correspond with any of the github accounts u mentioned in here. so you can't be really identified as the owner of the addon. 
but as I see the [addon repo](https://github.com/osmansonsuz/stremio-subtitle-addon) exists on your account, which makes you more probably the owner of the addon and not some hater who wants the addon down. can you confirm your ownership of this email address 'infinity@sonsuzanime.com'? 
IMO having your email in an addons description is a valid reason to request taking it down even if you couldn't prove that you are the creator of the addon

**Comment by osmansonsuz** [comment]
> @osmansonsuz just to clear things out. in the addon URL https://fdfa3f0d051a-one-piece-turkce-altyazi.baby-beamup.club/ one-piece-turkce-altyazi: is the addon name u specified while doing 'beamup init' fdfa3f0d051a: is a unique ID derived from your github username. and that ID doesn't correspond with any of the github accounts u mentioned in here. so you can't be really identified as the owner of the addon. but as I see the [addon repo](https://github.com/osmansonsuz/stremio-subtitle-addon) exists on your account, which makes you more probably the owner of the addon and not some hater who wants the addon down. can you confirm your ownership of this email address '[infinity@sonsuzanime.com](mailto:infinity@sonsuzanime.com)'? IMO having your email in an addons description is a valid reason to request taking it down even if you couldn't prove that you are the creator of the addon

I have access to infinity@sonsuzanime.com email. Where should i contact you from this email ?

**Comment by gcalcaterra** [comment]
@osmansonsuz send me a mail to gus@stremio.com from infinity@sonsuzanime.com asking for the deletion of the addon, please. We'll use that way to confirm ownership this time.

**Comment by osmansonsuz** [comment]
> @osmansonsuz send me a mail to [gus@stremio.com](mailto:gus@stremio.com) from [infinity@sonsuzanime.com](mailto:infinity@sonsuzanime.com) asking for the deletion of the addon, please. We'll use that way to confirm ownership this time.

Done. Can you check your email ?
