### ISSUE TITLE
dynamic addon goes rampant

### ISSUE THREAD

**Issue by lpuglia** [Stremio/stremio-beamup#54]
I'm trying to deploy my addon:
https://github.com/lpuglia/prova

this addon has a dynamic component that scrapes some urls to generate the metas and streams, at the moment when i do `beamup logs` i get a mess of outputs that belongs to old `HEAD` of the `master`, i'm not sure if i'm handling this correctly as the served manifest here:
https://6ef53e8aac88-itatv.baby-beamup.club/
do not reflect the latest change i made to it. 

Is this normal behavior? is it possible to completely stop the service and start from scratch?

**Comment by dexter21767-dev** [comment]
the changes aren't reflecting cuz it seems that your manifest is getting cached, did you deploy again using `beamup deploy` after the changes, tho?

**Comment by lpuglia** [comment]
it was just a problem of cache
