### ISSUE TITLE
Install/run puppeteer module on beamup?

### ISSUE THREAD

**Issue by svetlozardraganov** [Stremio/stremio-beamup#55]
I managed to successfully deploy stremio add-on that is relying on puppeteer library on beamup. Unfortunately I got errors for missing chrome/puppeteer installation I don't know how to tackle.

Is it possible to install and run puppeteer module in beamup servers? Any guidance would be much appreciated!

**Comment by dexter21767-dev** [comment]
It's not wise to run puppeteer on any free web hosting.

**Comment by svetlozardraganov** [comment]
That's good to know.

The only reason to do it is to login and to store credential. I tried with other libraries but they didn't work.
In addition to that I have minimized the traffic by disabling images, and I'm opening a single tab and single page only. So it's very optimal usage in terms of memory usage and traffic.

I agree it's not as optimal as other libraries but definitely not heavy at all.

Any advices what for alternative libraries with support for cookies and login capabilities?

**Comment by dexter21767-dev** [comment]
@svetlozardraganov u can use axios + axios-cookiejar-support + tough-cookie for cookies and login capabilities. and if u got stuck, just send me the repo and i will give u a hand.

**Comment by dexter21767-dev** [comment]
@svetlozardraganov i don't understand why you're using an XML validator for validating HTML.
I agree that Cherio isn't really intuitive to work with. i have used fast-html-parser and node-html-parser in the past (they are limited in how u can query elements iirc) but still usable.
also note that the website you're trying to scrape has a rate limit. and u need some time between requests.

**Comment by svetlozardraganov** [comment]
Thanks @dexter21767-dev 

I used the validators because the Cherio library didn't properly extracted web-elements using xpath-selectors.
In the past I have tried using css-selectors but they weren't that reliable as the xpath-ones. 
Nevertheless I decoded tp use the Chrerio library with css selectors and so far everything works great.

Can you provide more details about the website rate-limit? Where I can get this information and how should I handle it in my code? Is it as simple as using setTimeout() or I should use something else?

Thanks in advance.

**Comment by dexter21767-dev** [comment]
@svetlozardraganov sorry, i thought i replied. iirc setTimeout should be enough, u should experiment to find the correct values to use.
